// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDo6HIvybBmTlBL0HoArYUbEhUu0Hon4Ew',
    appId: '1:744239967971:web:d10d9a3475728bd897dfd6',
    messagingSenderId: '744239967971',
    projectId: 'firebasefoodproject',
    authDomain: 'fir-foodproject.firebaseapp.com',
    storageBucket: 'firebasefoodproject.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBpyXn-oHke_xNB243fPT_buy84lfoG2tc',
    appId: '1:744239967971:android:b52d496c8c19eae197dfd6',
    messagingSenderId: '744239967971',
    projectId: 'firebasefoodproject',
    storageBucket: 'firebasefoodproject.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCLMuiUlq6jV9rlNgyM3kfUYRlrRNI8pC0',
    appId: '1:744239967971:ios:c458ab9ee570745a97dfd6',
    messagingSenderId: '744239967971',
    projectId: 'firebasefoodproject',
    storageBucket: 'firebasefoodproject.appspot.com',
    iosClientId: '744239967971-p7knlcbr6pri8am98efv8rfrnq0aaf36.apps.googleusercontent.com',
    iosBundleId: 'com.dh.crewinflutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCLMuiUlq6jV9rlNgyM3kfUYRlrRNI8pC0',
    appId: '1:744239967971:ios:c458ab9ee570745a97dfd6',
    messagingSenderId: '744239967971',
    projectId: 'firebasefoodproject',
    storageBucket: 'firebasefoodproject.appspot.com',
    iosClientId: '744239967971-p7knlcbr6pri8am98efv8rfrnq0aaf36.apps.googleusercontent.com',
    iosBundleId: 'com.dh.crewinflutter',
  );
}
